export const storeProducts = [
  {
    "slug": "smg-dwp-2200-050",
    "title": "96-Well 2.2 mL Deep-Well Extraction Plates, V-Bottom – Case of 50 (Sterile)",
    "sku": "SMG-DWP-2200-050",
    "price": 149,
    "category": "Extraction Consumables",
    "descriptionHtml": "<p>SMG sterile 96-well 2.2 mL deep-well extraction plates are designed for automated magnetic-bead nucleic acid extraction and high-throughput sample processing. Square wells support efficient mixing, while conical V-bottom geometry helps reduce residual sample volume and supports magnetic-bead collection.</p><h3>Key Features</h3><ul>\n<li>Sterile 96-well deep-well format</li>\n<li>2.2 mL working volume per well</li>\n<li>Square wells with conical V-bottom geometry</li>\n<li>High-quality polypropylene construction</li>\n<li>Transparent plate construction</li>\n<li>RNase/DNase-free and pyrogen-free</li>\n<li>Resistant to common laboratory buffers, alcohols, and wash solutions</li>\n<li>Temperature range: -80°C to 121°C</li>\n<li>Compatible with heat-sealing film, aluminum foil seals, and silicone sealing mats</li>\n<li>Suitable for compatible automated magnetic-bead extraction workflows</li>\n<li>Manufactured in a controlled cleanroom environment</li>\n</ul><h3>Applications</h3><ul>\n<li>DNA purification</li>\n<li>RNA purification</li>\n<li>Total nucleic acid purification</li>\n<li>Automated magnetic-bead extraction</li>\n<li>High-throughput sample processing</li>\n</ul><h3>Packaging &amp; Ordering</h3><ul>\n<li>5 sterile plates per bag</li>\n<li>10 bags per SMG case</li>\n<li>50 plates per case</li>\n<li><strong>Ordering quantity: 1 = 1 case (50 plates)</strong></li>\n<li><strong>Minimum order: 10 cases / 500 plates per item</strong></li>\n</ul><p><strong>Lead Time:</strong> Please allow approximately 4–6 weeks for products requiring overseas fulfillment. Lead times may vary based on order volume, production schedules, customs clearance, and freight conditions.</p><h3>Compatibility Notice</h3><p>Customers should confirm instrument, protocol, and consumable compatibility before ordering. References to third-party platforms are provided solely to describe compatibility and do not imply affiliation with or endorsement by the respective manufacturer.</p><p><strong>For laboratory use only.</strong></p>",
    "image": "https://cdn.shopify.com/s/files/1/0751/7808/2440/files/08862040-4103-4a31-bc46-503bc3eaea3b2.2logo.png?v=1790620264",
    "imageAlt": "SMG sterile 96-well 2.2 mL V-bottom deep-well extraction plate"
  },
  {
    "slug": "smg-mrs-0096-050",
    "title": "96-Well Magnetic Rod Sleeve Tip Combs – Case of 50 (Sterile)",
    "sku": "SMG-MRS-0096-050",
    "price": 175,
    "category": "Extraction Consumables",
    "descriptionHtml": "<p>SMG sterile 96-position magnetic rod sleeve tip combs are designed for high-throughput magnetic-bead nucleic acid extraction workflows using compatible 2.2 mL 96-well deep-well plates. The sleeves protect instrument magnetic rods from direct contact with samples and reagents while supporting magnetic-bead transfer throughout binding, washing, and elution steps.</p><h3>Key Features</h3><ul>\n<li>Sterile 96-position format</li>\n<li>Medical-grade polypropylene construction</li>\n<li>Transparent construction</li>\n<li>Designed for use with compatible 2.2 mL 96-well deep-well plates</li>\n<li>RNase/DNase-free and pyrogen-free</li>\n<li>Uniform wall thickness and smooth surface</li>\n<li>Helps protect magnetic rods from direct sample and reagent contact</li>\n<li>Supports magnetic-bead mixing, binding, washing, and elution</li>\n<li>Autoclavable at 121°C for 20 minutes</li>\n<li>Suitable for compatible automated DNA, RNA, and total nucleic acid extraction workflows</li>\n</ul><h3>Applications</h3><ul>\n<li>Magnetic-bead nucleic acid extraction</li>\n<li>DNA purification</li>\n<li>RNA purification</li>\n<li>Total nucleic acid purification</li>\n<li>High-throughput molecular sample preparation</li>\n</ul><h3>Packaging &amp; Ordering</h3><ul>\n<li>2 sterile tip combs per bag</li>\n<li>25 bags per SMG case</li>\n<li>50 tip combs per case</li>\n<li><strong>Ordering quantity: 1 = 1 case (50 tip combs)</strong></li>\n<li><strong>Minimum order: 10 cases / 500 tip combs per item</strong></li>\n</ul><p><strong>Lead Time:</strong> Please allow approximately 4–6 weeks for products requiring overseas fulfillment. Lead times may vary based on order volume, production schedules, customs clearance, and freight conditions.</p><h3>Compatibility Notice</h3><p>Customers should confirm instrument, extraction protocol, and deep-well plate compatibility before ordering. References to third-party platforms are provided solely to describe compatibility and do not imply affiliation with or endorsement by the respective manufacturer.</p><p><strong>For laboratory use only.</strong></p>",
    "image": "https://cdn.shopify.com/s/files/1/0751/7808/2440/files/rodcoverlogo.png?v=1790620266",
    "imageAlt": "SMG sterile 96-position magnetic rod sleeve tip comb"
  },
  {
    "slug": "smg-elp-0500-050",
    "title": "96-Well 0.5 mL Elution Plates, V-Bottom – Case of 50 (Sterile)",
    "sku": "SMG-ELP-0500-050",
    "price": 149,
    "category": "Extraction Consumables",
    "descriptionHtml": "<p>SMG sterile 96-well 0.5 mL elution plates are designed for elution, nucleic acid extraction, sample storage, and high-throughput liquid-handling workflows. Square wells with conical V-bottom geometry support efficient sample recovery, consistent mixing, and low residual volume.</p><h3>Key Features</h3><ul>\n<li>Sterile 96-well format</li>\n<li>0.5 mL working capacity per well</li>\n<li>Square wells with conical V-bottom geometry</li>\n<li>High-quality polypropylene construction</li>\n<li>Clear plate with visible alphanumeric markings</li>\n<li>RNase/DNase-free, pyrogen-free, and free of human DNA</li>\n<li>Resistant to common laboratory buffers and chemicals</li>\n<li>Temperature range: -80°C to 121°C</li>\n<li>Autoclavable at 121°C for 20 minutes</li>\n<li>Compatible with adhesive seals, heat-sealing films, storage caps, and silicone sealing mats</li>\n<li>Suitable for compatible automated and manual liquid-handling workflows</li>\n</ul><h3>Applications</h3><ul>\n<li>Elution and sample collection</li>\n<li>Magnetic-bead nucleic acid extraction</li>\n<li>DNA and RNA purification</li>\n<li>Sample storage</li>\n<li>Serial dilution and reagent transfer</li>\n</ul><h3>Packaging &amp; Ordering</h3><ul>\n<li>10 sterile plates per bag</li>\n<li>5 bags per SMG case</li>\n<li>50 plates per case</li>\n<li><strong>Ordering quantity: 1 = 1 case (50 plates)</strong></li>\n<li><strong>Minimum order: 10 cases / 500 plates per item</strong></li>\n</ul><p><strong>Lead Time:</strong> Please allow approximately 4–6 weeks for products requiring overseas fulfillment. Lead times may vary based on order volume, production schedules, customs clearance, and freight conditions.</p><h3>Compatibility Notice</h3><p>Customers should confirm instrument, protocol, and consumable compatibility before ordering. References to third-party platforms are provided solely to describe compatibility and do not imply affiliation with or endorsement by the respective manufacturer.</p><p><strong>For laboratory use only.</strong></p>",
    "image": "https://cdn.shopify.com/s/files/1/0751/7808/2440/files/0.5mlelutionlogo.png?v=1790620261",
    "imageAlt": "SMG sterile 96-well 0.5 mL V-bottom elution plate"
  },
  {
    "slug": "smg-pcr-0384-050",
    "title": "384-Well Clear Optical PCR Plates, Full-Skirted – Case of 50 (Sterile)",
    "sku": "SMG-PCR-0384-050",
    "price": 199,
    "category": "PCR Consumables",
    "descriptionHtml": "<p>SMG sterile 384-well clear optical PCR plates are designed for high-throughput PCR, real-time PCR (qPCR), and automated laboratory workflows. The full-skirted, low-profile format supports dependable positioning in compatible 384-well instruments and liquid-handling systems.</p><h3>Key Features</h3><ul>\n<li>Sterile 384-well format</li>\n<li>Maximum well volume: 40 µL</li>\n<li>Clear, full-skirted, low-profile construction</li>\n<li>Uniform thin-walled wells for consistent heat transfer</li>\n<li>Raised well rims support secure sealing and help reduce evaporation</li>\n<li>Cutaway corners at A24 and P24 for plate orientation</li>\n<li>Molded alphanumeric markings for sample identification</li>\n<li>Manufactured from virgin medical-grade polypropylene</li>\n<li>RNase-, DNase-, and DNA-free; free of PCR inhibitors</li>\n<li>Tested pyrogen- and endotoxin-free</li>\n</ul><h3>Applications</h3><ul>\n<li>High-throughput PCR</li>\n<li>Real-time PCR and qPCR</li>\n<li>DNA amplification</li>\n<li>Sequencing workflows</li>\n<li>Automated reaction setup</li>\n</ul><h3>Packaging &amp; Ordering</h3><ul>\n<li>10 sterile plates per box</li>\n<li>5 boxes per SMG case</li>\n<li>50 plates per case</li>\n<li><strong>Ordering quantity: 1 = 1 case (50 plates)</strong></li>\n<li><strong>Minimum order: 10 cases / 500 plates per item</strong></li>\n</ul><p><strong>Lead Time:</strong> Please allow approximately 4–6 weeks for products requiring overseas fulfillment. Lead times may vary based on order volume, production schedules, customs clearance, and freight conditions.</p><h3>Compatibility Notice</h3><p>Customers should confirm instrument, protocol, and consumable compatibility before ordering. References to third-party platforms are provided solely to describe compatibility and do not imply affiliation with or endorsement by the respective manufacturer.</p><p><strong>For laboratory use only.</strong></p>",
    "image": "https://cdn.shopify.com/s/files/1/0751/7808/2440/files/384wellplatelogo.png?v=1790620259",
    "imageAlt": "SMG sterile 384-well clear full-skirted optical PCR plate"
  }
];
export const money = (amount: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
